---
title: "Readme. Taller datos Inside Airbnb"
author: "Taller MAT3 GIN 24-25"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
    number_sections: true
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Taller de Datos: Inside Airbnb

#### Contexto de los Datos 

La plataforma [Inside Airbnb](http://insideairbnb.com/) recopila y pone a disposici칩n informaci칩n detallada sobre apartamentos y residencias vacacionales en alquiler en diversas ubicaciones alrededor del mundo. Este sitio constituye una herramienta valiosa para analizar la oferta de Airbnb en distintas regiones, desde provincias y departamentos hasta condados y barrios.

Los datos disponibles son de acceso libre bajo una [licencia Open Source](https://www.redhat.com/es/topics/open-source/what-is-open-source), lo que permite su uso y an치lisis siempre que se respeten las condiciones especificadas en la [licencia del proyecto](http://insideairbnb.com/about.html). Si quieres sumergirte en el mundo de los datos y explorar sus posibilidades, puedes comenzar desde la [p치gina principal de Inside Airbnb](http://insideairbnb.com/get-the-data.html) o consultar los recursos espec칤ficos que se detallan a continuaci칩n.

#### Recursos de Datos Disponibles

- **[Obtener datos](http://insideairbnb.com/get-the-data.html):** Enlace directo para descargar los datos.
- **[Diccionario de Datos](https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4/edit#gid=982310896):** Documentaci칩n detallada sobre las variables disponibles.
- **[Pol칤ticas de Datos](http://insideairbnb.com/data-policies.html):** Informaci칩n sobre la disponibilidad de datos en relaci칩n con la misi칩n del proyecto y las directrices de la comunidad.
- **[Solicitud de Datos](http://insideairbnb.com/data-requests.html):** Herramienta para acceder a datos archivados o de nuevas regiones (ten en cuenta que este servicio es de pago para datos de m치s de un a침o de antig칲edad).

#### 춰Atenci칩n!
Si deseas consultar datos hist칩ricos que excedan un a침o, deber치s recurrir al servicio de solicitud de datos, el cual implica un costo.

---

### Acceso y Descarga de los Datos

A trav칠s del enlace **[Get the data](http://insideairbnb.com/get-the-data.html)** puedes descargar diferentes archivos para cada ciudad, descritos en la siguiente tabla:

| **Nombre del Archivo**       | **Descripci칩n**                                                                                      |  
|-------------------------------|------------------------------------------------------------------------------------------------------|  
| **listings.csv.gz**           | Datos detallados de las propiedades en la ciudad seleccionada.                                       |  
| **calendar.csv.gz**           | Datos detallados sobre la disponibilidad y precios de las propiedades en la ciudad.                 |  
| **reviews.csv.gz**            | Datos detallados de las rese침as relacionadas con las propiedades en la ciudad.                      |  
| **listings.csv**              | Informaci칩n resumida y m칠tricas generales, ideal para visualizaciones.                              |  
| **reviews.csv**               | Datos resumidos de rese침as, 칰tiles para an치lisis temporales vinculados a cada propiedad.            |  
| **neighbourhoods.csv**        | Listado de vecindarios utilizados como filtro geogr치fico, basado en datos de la ciudad o fuentes GIS. |  
| **neighbourhoods.geojson**    | Archivo GeoJSON con las delimitaciones de los vecindarios de la ciudad.                             |  

춰Explorar estos datos es una gran oportunidad para visualizar y analizar las din치micas del mercado de alquiler vacacional en distintas regiones del mundo! 游꿢